global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
    - targets: ['localhost:9090']
  - job_name: redis_exporter
    static_configs:
    - targets: ['mwgg-prometheus-redis-exporter:9121']