name: CI

on:
  push:
    tags: [ release/client/* ]

jobs:
  publish-bundle:
    runs-on: ubuntu-20.04
      
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.x

      - name: Cake script
        uses: cake-build/cake-action@v1
        with:
          verbosity: Diagnostic
          script-path: ./mod-bepinex-client/build.cake

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install script dependencies
        uses: borales/actions-yarn@v4.2.0
        with:
          cmd: install
          dir: ./mod-bepinex-client/script

      - name: Publish bundle
        run: node createBundle.js
        working-directory: ./mod-bepinex-client/script
        env:
          SUPABASE_BASE_API_URL: ${{ vars.SUPABASE_BASE_API_URL }}
          SUPABASE_SERVICE_ROLE_TOKEN: ${{ secrets.SUPABASE_SERVICE_ROLE_TOKEN }}